http:
  routers:
    web:
      rule: Host(`web.localhost`)
      entryPoints:
        - web
      service: web

    api:
      rule: Host(`api.localhost`)
      entryPoints:
        - web
      service: api

    prometheus:
      rule: Host(`prometheus.localhost`)
      entryPoints:
        - web
      service: prometheus

    grafana:
      rule: Host(`grafana.localhost`)
      entryPoints:
        - web
      service: grafana

    traefik:
      rule: Host(`traefik.localhost`)
      entryPoints:
        - web
      service: api@internal

  services:
    web:
      loadBalancer:
        servers:
          - url: http://web:3000

    api:
      loadBalancer:
        servers:
          - url: http://api:8000

    prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090

    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
