services:
  traefik:
    ports:
      - "${TRAEFIK_PORT:-80}:80"

  api:
    environment:
      APP_ENV: development

  web:
    environment:
      NODE_ENV: production

  prometheus:
    environment:
      APP_ENV: development
