"""add food catalog"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260408_0007"
down_revision: str | None = "20260408_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

FOOD_SEED = [
    {
        "name": "Pechuga de pollo",
        "category_code": "protein",
        "portion_label": "100 g cocidos",
        "portion_grams": 100,
        "energy_kcal": 165,
        "protein_g": 31,
        "fat_g": 3.6,
        "carbs_g": 0,
        "is_active": True,
    },
    {
        "name": "Atun en agua",
        "category_code": "protein",
        "portion_label": "1 lata drenada",
        "portion_grams": 120,
        "energy_kcal": 132,
        "protein_g": 28,
        "fat_g": 1.0,
        "carbs_g": 0,
        "is_active": True,
    },
    {
        "name": "Huevo",
        "category_code": "protein",
        "portion_label": "2 piezas",
        "portion_grams": 100,
        "energy_kcal": 143,
        "protein_g": 12.6,
        "fat_g": 9.5,
        "carbs_g": 1.1,
        "is_active": True,
    },
    {
        "name": "Yogur griego natural",
        "category_code": "dairy",
        "portion_label": "170 g",
        "portion_grams": 170,
        "energy_kcal": 100,
        "protein_g": 17,
        "fat_g": 0,
        "carbs_g": 6,
        "is_active": True,
    },
    {
        "name": "Queso cottage",
        "category_code": "dairy",
        "portion_label": "1/2 taza",
        "portion_grams": 110,
        "energy_kcal": 98,
        "protein_g": 11,
        "fat_g": 4.3,
        "carbs_g": 3.4,
        "is_active": True,
    },
    {
        "name": "Avena",
        "category_code": "carb",
        "portion_label": "40 g crudos",
        "portion_grams": 40,
        "energy_kcal": 156,
        "protein_g": 5.4,
        "fat_g": 2.8,
        "carbs_g": 26.5,
        "is_active": True,
    },
    {
        "name": "Arroz cocido",
        "category_code": "carb",
        "portion_label": "1 taza",
        "portion_grams": 158,
        "energy_kcal": 205,
        "protein_g": 4.3,
        "fat_g": 0.4,
        "carbs_g": 44.5,
        "is_active": True,
    },
    {
        "name": "Tortilla de maiz",
        "category_code": "carb",
        "portion_label": "2 piezas",
        "portion_grams": 60,
        "energy_kcal": 124,
        "protein_g": 3.2,
        "fat_g": 1.6,
        "carbs_g": 25.2,
        "is_active": True,
    },
    {
        "name": "Pan integral",
        "category_code": "carb",
        "portion_label": "2 rebanadas",
        "portion_grams": 56,
        "energy_kcal": 138,
        "protein_g": 6.8,
        "fat_g": 2.2,
        "carbs_g": 23.6,
        "is_active": True,
    },
    {
        "name": "Papa cocida",
        "category_code": "carb",
        "portion_label": "150 g",
        "portion_grams": 150,
        "energy_kcal": 130,
        "protein_g": 3.0,
        "fat_g": 0.2,
        "carbs_g": 30.0,
        "is_active": True,
    },
    {
        "name": "Aguacate",
        "category_code": "fat",
        "portion_label": "50 g",
        "portion_grams": 50,
        "energy_kcal": 80,
        "protein_g": 1.0,
        "fat_g": 7.4,
        "carbs_g": 4.3,
        "is_active": True,
    },
    {
        "name": "Crema de cacahuate",
        "category_code": "fat",
        "portion_label": "1 cucharada",
        "portion_grams": 16,
        "energy_kcal": 94,
        "protein_g": 3.5,
        "fat_g": 8.0,
        "carbs_g": 3.2,
        "is_active": True,
    },
    {
        "name": "Aceite de oliva",
        "category_code": "fat",
        "portion_label": "1 cucharadita",
        "portion_grams": 5,
        "energy_kcal": 45,
        "protein_g": 0,
        "fat_g": 5.0,
        "carbs_g": 0,
        "is_active": True,
    },
    {
        "name": "Espinaca",
        "category_code": "vegetable",
        "portion_label": "1 taza cocida",
        "portion_grams": 180,
        "energy_kcal": 41,
        "protein_g": 5.3,
        "fat_g": 0.5,
        "carbs_g": 6.8,
        "is_active": True,
    },
    {
        "name": "Brocoli",
        "category_code": "vegetable",
        "portion_label": "1 taza cocida",
        "portion_grams": 156,
        "energy_kcal": 55,
        "protein_g": 3.7,
        "fat_g": 0.6,
        "carbs_g": 11.2,
        "is_active": True,
    },
    {
        "name": "Calabacita",
        "category_code": "vegetable",
        "portion_label": "1 taza cocida",
        "portion_grams": 180,
        "energy_kcal": 31,
        "protein_g": 2.4,
        "fat_g": 0.6,
        "carbs_g": 5.7,
        "is_active": True,
    },
    {
        "name": "Manzana",
        "category_code": "fruit",
        "portion_label": "1 pieza mediana",
        "portion_grams": 182,
        "energy_kcal": 95,
        "protein_g": 0.5,
        "fat_g": 0.3,
        "carbs_g": 25.1,
        "is_active": True,
    },
    {
        "name": "Platano",
        "category_code": "fruit",
        "portion_label": "1 pieza mediana",
        "portion_grams": 118,
        "energy_kcal": 105,
        "protein_g": 1.3,
        "fat_g": 0.4,
        "carbs_g": 27.0,
        "is_active": True,
    },
    {
        "name": "Frutos rojos",
        "category_code": "fruit",
        "portion_label": "1 taza",
        "portion_grams": 140,
        "energy_kcal": 70,
        "protein_g": 1.0,
        "fat_g": 0.5,
        "carbs_g": 17.0,
        "is_active": True,
    },
]


def upgrade() -> None:
    op.create_table(
        "food_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "category_code",
            sa.Enum(
                "protein",
                "carb",
                "fat",
                "vegetable",
                "fruit",
                "dairy",
                name="food_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("portion_label", sa.String(length=120), nullable=False),
        sa.Column("portion_grams", sa.Float(), nullable=True),
        sa.Column("energy_kcal", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_items_category_code"),
        "food_items",
        ["category_code"],
        unique=False,
    )
    op.create_index(op.f("ix_food_items_id"), "food_items", ["id"], unique=False)

    food_items = sa.table(
        "food_items",
        sa.column("name", sa.String),
        sa.column("category_code", sa.String),
        sa.column("portion_label", sa.String),
        sa.column("portion_grams", sa.Float),
        sa.column("energy_kcal", sa.Float),
        sa.column("protein_g", sa.Float),
        sa.column("fat_g", sa.Float),
        sa.column("carbs_g", sa.Float),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(food_items, FOOD_SEED)


def downgrade() -> None:
    op.drop_index(op.f("ix_food_items_id"), table_name="food_items")
    op.drop_index(op.f("ix_food_items_category_code"), table_name="food_items")
    op.drop_table("food_items")
