name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy env
        run: cp .env.example .env

      - name: Validate Docker Compose
        run: docker compose --env-file .env -f infra/compose/docker-compose.yml config
